apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data
configurations:
  - rollout-transform.yaml
resources:
  - kafdrop-deploy.yaml
  - kafdrop-service.yaml
  - kafka-service.yaml
  - nifi-deploy.yaml
  - nifi-ingress.yaml
  - nifi-pvc.yaml
  - nifi-service.yaml
  - zookeeper-deploy.yaml
  - zookeeper-service.yaml
